#!/bin/sh
# Host tests for the runtime: the copy of stdout/stderr into its log, Horizon
# file access (rights, descriptor modes, open-file path matching) and the
# analog-stick mouse cursor.
set -eu
root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
build="$(mktemp -d "${TMPDIR:-/tmp}/wine-nx-console.XXXXXX")"
trap 'rm -rf "$build"' EXIT HUP INT TERM
flags="-std=gnu11 -Wall -Wextra -Werror -fsanitize=address,undefined -fno-omit-frame-pointer"
"${CC:-clang}" $flags "$root/horizon-wine/tests/std_stream_lines.c" -o "$build/std_stream_lines"
"$build/std_stream_lines"
"${CC:-clang}" $flags -I"$root/include" "$root/horizon-wine/tests/horizon_file_access.c" -o "$build/file_access"
"$build/file_access"
"${CC:-clang}" $flags "$root/horizon-wine/tests/pointer_cursor.c" -o "$build/pointer_cursor"
"$build/pointer_cursor"
"${CC:-clang}" $flags "$root/horizon-wine/tests/pad_bindings.c" -o "$build/pad_bindings"
"$build/pad_bindings"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_message_queue.c" -o "$build/message_queue"
"$build/message_queue"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_win_timers.c" -o "$build/win_timers"
"$build/win_timers"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_msg_queue.c" -o "$build/msg_queue"
"$build/msg_queue"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_clipboard.c" -o "$build/clipboard"
"$build/clipboard"
"${CC:-clang}" $flags "$root/horizon-wine/tests/launcher_list.c" -o "$build/launcher_list"
"$build/launcher_list"
"${CC:-clang}" $flags "$root/horizon-wine/tests/launcher_settings.c" -o "$build/launcher_settings"
"$build/launcher_settings"
"${CC:-clang}" $flags "$root/horizon-wine/tests/launcher_pe.c" -o "$build/launcher_pe"
"$build/launcher_pe"
"${CC:-clang}" $flags "$root/horizon-wine/tests/sd_read_cache.c" -o "$build/sd_read_cache"
"${CC:-clang}" $flags "$root/horizon-wine/tests/sd_write_buffer.c" -o "$build/sd_write_buffer"
"${CC:-clang}" $flags "$root/horizon-wine/tests/sd_stat_cache.c" -o "$build/sd_stat_cache"
"$build/sd_stat_cache"
"$build/sd_write_buffer"
"$build/sd_read_cache"
"${CC:-clang}" $flags "$root/horizon-wine/tests/box64_code_arena.c" -o "$build/box64_code_arena"
"$build/box64_code_arena"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_registry.c" -o "$build/registry"
"$build/registry"
"${CC:-clang}" $flags "$root/horizon-wine/tests/registry_paths.c" -o "$build/registry_paths"
"$build/registry_paths"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_read_redirect.c" -o "$build/read_redirect"
"$build/read_redirect"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_object_dirs.c" -o "$build/object_dirs"
"$build/object_dirs"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_keyboard.c" -o "$build/keyboard"
"$build/keyboard"
"${CC:-clang}" $flags -D__WINESRC__ -DWINE_UNIX_LIB -D_WIN64 -I"$root/include" "$root/horizon-wine/tests/horizon_completion.c" -o "$build/completion"
"$build/completion"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_free_range.c" -o "$build/free_range"
"$build/free_range"
python3 "$root/horizon-wine/tests/check_horizon_va_search.py"
python3 "$root/horizon-wine/tests/check_horizon_guest_reserve.py"
python3 "$root/horizon-wine/tests/check_horizon_reservation_transition.py"
python3 "$root/horizon-wine/tests/check_horizon_reservation_bounds.py"
python3 "$root/horizon-wine/tests/check_horizon_thread_tls.py"
"${CC:-clang}" $flags -pthread -I"$root/horizon-wine/tests/horizon_virtmem" \
    "$root/horizon-wine/tests/horizon_virtmem.c" -o "$build/virtmem"
"$build/virtmem"
python3 "$root/horizon-wine/tests/check_commit_chunks.py"
python3 "$root/horizon-wine/tests/check_waitable_timer.py"
"${CC:-clang}" $flags -D__WINESRC__ -DWINE_UNIX_LIB -D_WIN64 \
    -I"$root/horizon-wine/tests/xinput-shims" -I"$root/include" \
    "$root/horizon-wine/tests/xinput_nx_pad.c" -o "$build/xinput_pad"
"$build/xinput_pad"
"${CC:-clang}" $flags "$root/horizon-wine/tests/thread_profile.c" -o "$build/thread_profile"
"$build/thread_profile"
python3 "$root/horizon-wine/tests/check_core_affinity.py"
"${CC:-clang}" $flags "$root/horizon-wine/tests/box64_options.c" -o "$build/box64_options"
"$build/box64_options"
"${CC:-clang}" $flags "$root/horizon-wine/tests/fex_options.c" -o "$build/fex_options"
"$build/fex_options"
"${CC:-clang}" $flags "$root/horizon-wine/tests/horizon_pool.c" -o "$build/horizon_pool"
python3 "$root/horizon-wine/tests/check_horizon_backings.py"
"$build/horizon_pool"
python3 "$root/horizon-wine/tests/check_horizon_backings.py"
"${CC:-clang}" $flags -pthread "$root/horizon-wine/tests/horizon_memfile.c" -o "$build/horizon_memfile"
"$build/horizon_memfile"
python3 "$root/horizon-wine/tests/check_horizon_sections.py"
python3 "$root/horizon-wine/tests/check_horizon_image_info.py"
python3 "$root/horizon-wine/tests/check_memory_status.py"
python3 "$root/horizon-wine/tests/check_user_profile.py"
python3 "$root/horizon-wine/tests/check_sims2_setup.py"
python3 "$root/horizon-wine/tests/check_sims2_layout.py"
python3 "$root/horizon-wine/tests/check_horizon_sock_bind.py"
python3 "$root/horizon-wine/tests/check_dxvk_payload.py"
python3 "$root/horizon-wine/tests/check_vulkan_wow64_mapping.py"
python3 "$root/horizon-wine/tests/check_d3dkmt_resources.py"
python3 "$root/horizon-wine/tests/check_package_amd64.py"
if [ -f "$root/horizon-wine/vendor/dxvk/src/dxvk/dxvk_device_info.cpp" ]; then
    python3 "$root/horizon-wine/tests/check_dxvk_requirements.py"
fi
